### PR TITLE
Requests percept implemented and fixed my_stakeholder and requests both work

### PR DESCRIPTION
**Pull request by hmyeh**
Fixed that the my_stakeholder_id and requests percept work at the same time.
Implemented the requests percept.

User story: As a GOAL agent I want to retrieve useful information so that the agent can use the request percept for actually being able to decide on the request.

### CODE REVIEW

**Comment by levilime** [comment]
Verified that it works in Goal, and the build passes

**Comment by levilime** [comment]
But in visibleforStakeholders I only get the Municipality stakeholder id in Goal. Getting only that ID is not so interesting. Is there a way to get the senderID as well?

**Comment by levilime** [comment]
Could you also add the price offered adding and maybe extending functionality of the BuyLandTest.getPriceFromPopup?

**Comment by dionytadema** [comment]
👍

**Pull request merged**
