### PR TITLE
Pull Request for percepts indicator_Link/4 and indicator/3

### PR DESCRIPTION
**Pull request by hmyeh**
User Story: As a programmer I want to create more percepts in the connector.

Added the percept for the indicator_Link, but changed the original stakeholder percept into this percept.
Added the percept for the indicator.
Added tests for both translator classes.

### CODE REVIEW

**Comment by dionytadema** [comment]
+1

**Comment by NickTUD** [comment]
Checkstyle = :+1: 
Cobertura = 75.1 % over the environment so :+1:
FindBugs = 1 bug detected but not in the code you changed, maybe a new task for a next sprint? Still :+1: 
PMD = _see file_
[pmd-report.txt](https://github.com/levilime/tygron/files/272033/pmd-report.txt)

**Comment by StefanV7** [comment]
Fixed some of the PMD violations. Some were unsolvable or required major changes. Also speaking for Hao Ming here.

**Comment by NickTUD** [comment]
Okay it's good so final :+1:

**Comment by dionytadema** [comment]
+1

**Pull request merged**
