### PR TITLE
Added Google_checks Checkstyle with custom supression script and other integrations

### PR DESCRIPTION
**Pull request by levilime**
User Story: As a programmer I want to make informed decisions on the quality of a merge request by using Continuous integration.

Because the connector is mostly code not written or maintained by us, we'll only do checkstyle on the code that we touch. In this way we provide strong arguments that we can do checkstyle well (by example) while not running in constantly correct checkstyle mistakes from the repo we fork off. This would be an uphill battle.

The python script on the server is run by using jython. This is because Travis only supports one development language per integration.

Cobertura fails when the line coverage for the Environment for a file is lower than 75%. 

PMD and Findbugs are just outputted in the Travis Log.

### CODE REVIEW

**Comment by NickTUD** [comment]
I thought we had decided to also implement cobertura today? You're also missing the user story in your opening comment.

**Comment by dionytadema** [comment]
+1

**Comment by levilime** [comment]
Diony's vote to merge does not count because he also worked on this ticket :smile:

**Comment by levilime** [comment]
Closed please merge #11 instead

**Pull request closed without merging**
